### Registro de Usuario
POST http://127.0.0.1:8001/api/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@mail.com",
    "password": "admin54321",
    "cpassword": "admin54321"
}

### Autenticación (Login)
POST http://127.0.0.1:8001/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}

### Login con Servidor
POST https://backapi.blumbit.net/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}

### Obtener el Perfil
GET http://127.0.0.1:8000/api/auth/profile
Accept: application/json
Authorization: Bearer 7|ugV6ueKI8chLRB3maClIIZuKlapoBJJlrwBzeNg3895f7160

### Salir (Logout)
POST http://127.0.0.1:8000/api/auth/logout
Accept: application/json
Authorization: Bearer 7|ugV6ueKI8chLRB3maClIIZuKlapoBJJlrwBzeNg3895f7160
