POST http://127.0.0.1:8000/api/nota
Accept: application/json
Authorization: Bearer 28|YEvqGvX0TSjks5TeDffds9uhoHuOydXllGBrUF5dce169b07
Content-Type: application/json

{
    "codigo_nota": "N004",
    "fecha_emision": "2025-06-27",
    "tipo_nota": "compra",
    "entidad_comercial_id": 3,
    "user_id": 1,
    "subtotal": 200,
    "impuestos": 0,
    "descuento_total": 30,
    "total_calculado": 500,
    "estado_nota": "ninguna",
    "observaciones": "Ninguna",
    "movimientos": [
        {
            "producto_id": 4,
            "almacen_id": 1,
            "cantidad": 7,
            "tipo_movimiento": "ingreso",
            "precio_unitario_compra": "200",
            "precio_unitario_venta": "300",
            "total_linea": "500",
            "observaciones": "NINGUNA"
        }
    ]
}

### venta

POST http://127.0.0.1:8000/api/nota
Accept: application/json
Authorization: Bearer 28|YEvqGvX0TSjks5TeDffds9uhoHuOydXllGBrUF5dce169b07
Content-Type: application/json

{
    "codigo_nota": "N005",
    "fecha_emision": "2025-06-28",
    "tipo_nota": "venta",
    "entidad_comercial_id": 3,
    "user_id": 1,
    "subtotal": 200,
    "impuestos": 0,
    "descuento_total": 30,
    "total_calculado": 500,
    "estado_nota": "ninguna",
    "observaciones": "Ninguna",
    "movimientos": [
        {
            "producto_id": 4,
            "almacen_id": 1,
            "cantidad": 7,
            "tipo_movimiento": "salida",
            "precio_unitario_compra": "200",
            "precio_unitario_venta": "300",
            "total_linea": "500",
            "observaciones": "NINGUNA"
        }
    ]
}

### Lista de Nota
GET http://127.0.0.1:8000/api/nota?tipo_nota=compra
Accept: application/json
Authorization: Bearer 28|YEvqGvX0TSjks5TeDffds9uhoHuOydXllGBrUF5dce169b07
